name: easy_stepper

description: A fully customizable, beautiful and easy to use stepper widget. It
  help you to show or collect information from users using organized steps.

version: 0.8.5+1

homepage: https://github.com/ma7moud3osman
repository: https://github.com/ma7moud3osman/easy_stepper.git
issue_tracker: https://github.com/ma7moud3osman/easy_stepper/issues

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
